import './globals.css'
import { Hind_Siliguri } from 'next/font/google'
import Header from '../app/components/Header'


import AosInit from './aos'

const HindSiliguri = Hind_Siliguri({
   subsets: ['latin'],
   weight: ['300','400','500', '600', '700'], 
 })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <AosInit/>
    
      <body className={HindSiliguri.className}>
      <Header/>
      {children}
      </body>
    </html>
  )
}
